name: First workflow
on: workflow_dispatch #manual trigger
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world!"
      - name: Multi print
        run: |
          echo "Multi 1"
          echo "Multi 2"
      - name: Print goodbye
        run: echo "Done, bye"
