name: Matrix strategy
on: workflow_dispatch #manual trigger
jobs:
  test:
    continue-on-error: true
    strategy:
      matrix:
        java-version: ['8','21']
        os: ['ubuntu-latest', 'windows-latest']
        include:
          - java-version: 22
            os: 'ubuntu-latest'
        exclude:
          - java-version: 8
            os: 'windows-latest'
    environment: qa
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Setup java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          architecture: x64

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test
