name: Workflow that reuses other workflow
on: workflow_dispatch
jobs:
  execute-self:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "Executed self"
  reuse:
    needs: execute-self
    uses: ./.github/workflows/reusable.yml
#    secrets:
#      some-secret: ${{ secrets.some-secrets }}
    with:
      simple-value: 'Value set explicitly'
  print-resuse-result:
    needs: reuse
    runs-on: ubuntu-latest
    steps:
      - name: Print result
        run: echo "${{ needs.reuse.outputs.workflow-outcome }}"